### ISSUE TITLE
Pikku juttuja joita voi korjata.

### ISSUE THREAD

**Issue by AnonRobAta** [huehue95/aimshake-croshair#1]
Voisi käyttää PlayerPedId() mielummin kuin GetPlayerPed(-1)
Siinä oli joku performance syy en muista mistä näin sen.

Sitten ton playerpedin voisi esim laittaa repeatilla että sitä ei tarvitse loopata. Esim:
local Ped = PlayerPedId()

repeat
    Ped = PlayerPedId()
until Ped ~= nil

ja toi sama tohon rivin 35 playerid()

Sitten 38 rivin local speed_
voisi siirtää 41 rivin yhden yläpuolelle.

Sitten vielä tohon 60 riviin laita waitti 1100

**Comment by huehue95** [comment]
Kiiti ty XD
